### ISSUE TITLE
sizeOf is incomplete and inaccurate

### ISSUE THREAD

**Issue by DavidBruant** [skale-me/skale-engine#52]
Taking a step back, it's impossible to assess accurately the size of a JavaScript value as it can varies across implementations and according to the context (especially for objects).
Also, I'm not sure how much the accuracy of the function matters, so I don't know whether giving feedback is any valuable to you.
That said, here is some feedback on https://github.com/skale-me/skale-engine/blob/master/lib/sizeof.js
## Boolean

Boolean being 4 bytes seems idiotic. In all reasonable cases, boolean object properties will certainly be 1 byte if not 1 bit (packed in a byte if there are several). At least, it's simple enough a optimization that implementations likely have done it.
## Number

For integers, it's very likely JS engines actually store them in 4 bytes instead of 8 as the spec suggests for numbers.
## String

I don't know for strings, but I know some time ago, the Mozilla JS team was considering storing ECMAScript strings as UTF-8 (or latin1) and only convert to the spec encoding if that becomes necessary because of subtle string manipulations, so UCS-2 should not be assumed from implementations (I don't know where V8 stands).
## Object

`obj instanceof Array` should certainly be `Array.isArray(obj)`. The array length probably takes 4 bytes as well.

Additionally, you probably want to distinguish Node's `Buffer`, because they'll likely be used as data and their size is deterministic (that's probably the only object type that is so).

Your object size does not take the "hidden class" size into account. Not sure how much that matters.

No clue how much a `Date` weighs, but your functions certainly guesses wrong as it does not look for "internal" properties.
## Symbols

In Node.js v6:

``` js
> typeof Symbol()
'symbol'
```

This case is not taken into account by your function. 0 will be returned now. Maybe it's fine, but at least the code should be explicit about it.

**Comment by mvertes** [comment]
Thanks for this lengthy explanation. You're right, it is impossible to assess accurately the size of JS objects, but here the purpose of sizeOf is only to provide a rough estimate of their memory space, to trigger or not spillToDisk.

So it should be renamed into roughSizeOf().

For information, this code is derived from https://www.npmjs.com/package/object-sizeof, but faster at providing the same results.

We need this function to be fast rather than accurate. It's better if the estimate is conservative.

Regarding the boolean size, it's probably a litteral int32 but I'm not sure. Buffers need to be added, and also Buffer.byteLenght(string) to be more accurate for strings (but again, i'm not sure how it is represented/stored internally, and how much to add for metadata overhead).

**Comment by DavidBruant** [comment]
>  the purpose of sizeOf is only to provide a rough estimate of their memory space, to trigger or not spillToDisk

I thought so, hence my foreword. What is the worst impact of a bad estimate?

That's fine if you're closing the issue as is. Maybe renaming and/or adding a comment with the explanations you provided would help other people skimming at the code.
