### ISSUE TITLE
Get rid of direct eval

### ISSUE THREAD

**Issue by DavidBruant** [skale-me/skale-engine#53]
https://github.com/skale-me/skale-engine/blob/907075ad2e1bc206986192e7bed155da581123c1/bin/worker.js#L204

Direct `eval` is dangerous. Regexp are terrible.

````
"use strict";

var str = "(() => { fs = 42 })()"
var fs = {};

console.log('pass', !!(str.match(/^\s*\([^)]*\)\s*=>/))) // passing the second regexp test
console.log('fs', fs) // {}
eval(str)
console.log('fs', fs) // 42. The direct-evaled code modified a variable value outside its scope
````

Among other things, someone can send a message like the one I showed and read and write to any variable of `worker.js`.
I have not been able to assess how much damage can be done via this method, but it looks like at least the entire filesystem is compromised. Maybe it's possible to compromise the master, not clear.

**At least**, you should be evaling via an indirect eval : 
`("indirect", eval)(str)` or `var indirectEval = eval; indirectEval(str)`.

But even then it's not sure it's a good idea. Maybe the `new Function` way should be the only allowed way to send functions. People won't die from typing `function`.

**Comment by mvertes** [comment]
Thanks for identifying this. I agree on using indirect `eval` instead of `eval`, so `eval` behaves like `new Function`. Regexp should also filter any invalid function definition. Additionally, we should also check that parameters of sources, actions and transformations which are supposed to be function definitions really are: `(typeof arg === 'function')`. This would catch potential problems at the source, and be done on master side. Ultimately, proper use of const would also forbid var overwriting. This will be done later.
